FROM alpine
MAINTAINER George Lewis <schvin@schvin.net>

ENV REFRESHED_AT 2015-09-18

# can be specified as command line flag
ENV LEVEL_TOKEN foo

ADD checkLevel-linux-amd64 /usr/sbin/check_level

ENTRYPOINT sh